name: chats
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  encrypt: ^5.0.3
  grpc: ^3.2.4
  jaguar_jwt: ^3.0.0
  protobuf: ^3.1.0
  stormberry: ^0.14.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.8
  lints: ^3.0.0
  test: ^1.24.0
